apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1  # Changed from nginx to app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1  # Changed from nginx to app1
    spec:
      containers:
      - name: app1  # Changed from nginx to app1
        image: nginx  # Replace with actual image of app1
      # image: myrepo/app1:latest  # Replace with actual image of app1
        ports:
        - containerPort: 80  # Assuming app1 runs on port 8080
